import { SiliconError, SiliconErrorCode } from '../../errors';
import NativeSilicon from '../../module';
import { GenerateKeyOpts } from "./types";

/**
 * Generate a key
 * 
 * @param alias 
 * @param opts 
 * @returns 
 */
export async function generateKey(alias: string, opts: GenerateKeyOpts): Promise<string> {
    const result = await NativeSilicon.genKey(alias, opts);
    if (!result.success) {
        throw new SiliconError()
    }

    return result.data;
}

/**
 * Delete a key with the specified alias.
 * 
 * @param alias 
 * @returns true if the key was deleted
 */
export async function deleteKey(alias: string): Promise<boolean> {
    const result = await NativeSilicon.deleteKey(alias);
    if (!result.success) {
        if (result.errorCode == 'DELETE_FAILED') {
            throw new SiliconError(SiliconErrorCode.DELETE_FAILED, result.errorMessage)
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`)
    }

    return result.data;
}

/**
 * USE WITH CAUTION.
 * 
 * When 'prefix' is undefined, this function deletes all keys generated by the entire app, 
 * not just the keys generated by react-native-silicon.
 * If you are using other libs (e.g., expo-secure-store) this will delete all keys generated by them too.
 * 
 * We recommended that you prefix all your key aliases so that you can bulk delete using the 'prefix' param as a filter.
 * 
 * @param prefix When set, only keys with the specified prefix will be deleted
 * @returns The number of keys that were deleted
 */
export async function deleteAllKeys(prefix?: string): Promise<number> {
    const result = await NativeSilicon.deleteAllKeys(prefix)
    if (!result.success) {
        if (result.errorCode == 'BULK_DELETE_FAILED') {
            throw new SiliconError(SiliconErrorCode.BULK_DELETE_FAILED, result.errorMessage)
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`)
    }

    return result.data;
}

/**
 * Checks for the existence of a key with the specified alias.
 * 
 * @param alias 
 * @returns true if the key exists
 */
export async function keyExists(alias: string): Promise<boolean> {
    const result = await NativeSilicon.keyExists(alias)
    if (!result.success) {
        if (result.errorCode == 'KEY_CHECK_FAILED') {
            throw new SiliconError(SiliconErrorCode.KEY_CHECK_FAILED, result.errorMessage)
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`)
    }

    return result.data;
}

export function listKeys() {

}

export function validateKey(alias: string) {

}

export function getPubKey(alias: string) {

}

export type BiometricsSupport = {
    available: boolean, 
    enrolled: boolean, 
    type: 'FaceID' | 'TouchID' | 'Biometrics' | 'None' 
}

export function getBiometricSupport(): BiometricsSupport {
    
}

export function attestKey(alias: string) {

}

export function isHardwareBacked(alias: string) {

}

