import { SiliconError, SiliconErrorCode } from '../../errors';
import NativeSilicon from '../../module';
import { isPlainObject } from '../../utils/validation';
import { GenerateKeyOpts, KeyInfo } from "./types";

// TODO: Validate use inputs in EVERY wrapper function
// EVERY param must be validated to ensure run-time safety

/**
 * Generate a key
 * 
 * @param alias 
 * @param opts 
 * @returns 
 */
export async function generateKey(alias: string, opts: GenerateKeyOpts): Promise<string> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

    if (!isPlainObject(opts)) {
        throw new TypeError("Silicon Error: 'opts' must be an object");
    }

    if (Object.hasOwn(opts, 'purposes')) {
        if (!Array.isArray(opts.purposes)) {
            throw new TypeError("Silicon Error: 'purposes' must be an array");
        }
    }

    // TODO: Finish opts validation

    const result = await NativeSilicon.genKey(alias, opts);
    if (!result.success) {
        switch (result.errorCode) {
            case "INVALID_ALGORITHM_PARAMETER":
                throw new SiliconError(SiliconErrorCode.INVALID_ALGORITHM_PARAMETER, result.errorMessage);

            case "STRONGBOX_NOT_SUPPORTED":
                throw new SiliconError(SiliconErrorCode.STRONGBOX_NOT_SUPPORTED, result.errorMessage);
            
            case "PURPOSE_WRAP_NOT_SUPPORTED":
                throw new SiliconError(SiliconErrorCode.PURPOSE_WRAP_NOT_SUPPORTED, result.errorMessage);
            
            case "PURPOSE_AGREE_NOT_SUPPORTED":
                throw new SiliconError(SiliconErrorCode.PURPOSE_AGREE_NOT_SUPPORTED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/**
 * Delete a key with the specified alias.
 * 
 * @param alias 
 * @returns true if the key was deleted
 */
export async function deleteKey(alias: string): Promise<boolean> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }
    
    const result = await NativeSilicon.deleteKey(alias);
    if (!result.success) {
        if (result.errorCode == 'DELETE_FAILED') {
            throw new SiliconError(SiliconErrorCode.DELETE_FAILED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/**
 * USE WITH CAUTION.
 * 
 * When 'prefix' is undefined, this function deletes all keys generated by the entire app, 
 * not just the keys generated by react-native-silicon.
 * If you are using other libs (e.g., expo-secure-store) this will delete all keys generated by them too.
 * 
 * We recommended that you prefix all your key aliases so that you can bulk delete using the 'prefix' param as a filter.
 * 
 * @param prefix When set, only keys with the specified prefix will be deleted
 * @returns The number of keys that were deleted
 */
export async function deleteAllKeys(prefix?: string): Promise<number> {
    if (prefix && typeof prefix !== 'string') {
        throw new TypeError("Silicon Error: 'prefix' must be of type string");
    }

    const result = await NativeSilicon.deleteAllKeys(prefix);
    if (!result.success) {
        if (result.errorCode == 'BULK_DELETE_FAILED') {
            throw new SiliconError(SiliconErrorCode.BULK_DELETE_FAILED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/**
 * Checks for the existence of a key with the specified alias.
 * 
 * @param alias 
 * @returns true if the key exists
 */
export async function keyExists(alias: string): Promise<boolean> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

    const result = await NativeSilicon.keyExists(alias);
    if (!result.success) {
        if (result.errorCode == 'KEY_CHECK_FAILED') {
            throw new SiliconError(SiliconErrorCode.KEY_CHECK_FAILED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/**
 * Lists all keys.
 * 
 * prefix can be defined to list only keys with a matching prefix.
 * 
 * @param prefix 
 * @returns An array of the key aliases
 */
export async function listKeys(prefix?: string): Promise<string[]> {
    if (prefix && typeof prefix !== 'string') {
        throw new TypeError("Silicon Error: 'prefix' must be of type string");
    }

    const result = await NativeSilicon.listKeys(prefix)
    if (!result.success) {
        if (result.errorCode == 'KEY_LIST_FAILED') {
            throw new SiliconError(SiliconErrorCode.KEY_LIST_FAILED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

export function validateKey(alias: string) {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

}

/**
 * Gets the pubkey from an asymmetric keypair.
 * @param alias 
 * @param format 
 * @returns 
 */
export async function getPubKey(alias: string, format: 'PEM' | 'B64'): Promise<string> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

    if (typeof format !== 'string' || 
        (format !== 'PEM' && format !== 'B64')
    ) {
        throw new TypeError("Silicon Error: 'format' must be of type 'PEM' | 'B64'");
    }

    const result = await NativeSilicon.getPubKey(alias, format);
    if (!result.success) {
        switch (result.errorCode) {
            case 'KEY_NOT_FOUND':
                throw new SiliconError(SiliconErrorCode.KEY_NOT_FOUND, result.errorMessage)

            case 'NO_CERT':
                throw new SiliconError(SiliconErrorCode.NO_CERT, result.errorMessage)

            case 'UNSUPPORTED_KEY_FAMILY':
                throw new SiliconError(SiliconErrorCode.UNSUPPORTED_KEY_FAMILY, result.errorMessage)

            case 'GET_PUB_KEY_FAILED':
                throw new SiliconError(SiliconErrorCode.GET_PUB_KEY_FAILED, result.errorMessage)
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/**
 * IMPORTANT: This will only work if an attestation challenge was provided when the
 * key was generated (see the generateKey options)
 * 
 * @param alias
 * @returns The certificate chain - An array of PEM strings
 */
export async function attestKey(alias: string): Promise<string[]> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

    const result = await NativeSilicon.attestKey(alias)
    if (!result.success) {
        switch (result.errorCode) {
            case 'KEY_NOT_FOUND':
                throw new SiliconError(SiliconErrorCode.KEY_NOT_FOUND, result.errorMessage);

            case 'NO_CERT_CHAIN':
                throw new SiliconError(SiliconErrorCode.NO_CERT_CHAIN, result.errorMessage)

            case 'ATTEST_FAILED':
                throw new SiliconError(SiliconErrorCode.ATTEST_FAILED, result.errorMessage)
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

export async function getKeyInfo(alias: string): Promise<KeyInfo> {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }

    const result = await NativeSilicon.getKeyInfo(alias)
    if (!result.success) {
        switch (result.errorCode) {
            case 'KEY_NOT_FOUND':
                throw new SiliconError(SiliconErrorCode.KEY_NOT_FOUND, result.errorMessage);

            case 'GET_KEY_INFO_FAILED':
                throw new SiliconError(SiliconErrorCode.GET_KEY_INFO_FAILED, result.errorMessage);

            case 'UNSUPPORTED_KEY_FAMILY':
                throw new SiliconError(SiliconErrorCode.UNSUPPORTED_KEY_FAMILY, result.errorMessage);

            case 'KEY_LOAD_FAILED':
                throw new SiliconError(SiliconErrorCode.KEY_LOAD_FAILED, result.errorMessage);
        }

        throw new SiliconError(SiliconErrorCode.UNKNOWN_NATIVE_ERROR, `${result.errorCode}: ${result.errorMessage}`);
    }

    return result.data;
}

/*
export function isHardwareBacked(alias: string) {
    if (!alias || typeof alias !== 'string') {
        throw new TypeError("Silicon Error: 'alias' must be of type string and not empty");
    }
}
*/

