plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

dependencies {
    implementation 'androidx.biometric:biometric:1.4.0-alpha06' // Use the latest stable/alpha for robust API 30+ support
}

group = 'co.alephnull.reactnative.silicon'
version = '0.1.0'

android {
  namespace "co.alephnull.reactnative.silicon"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
